version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "4000:4000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/battleship
    depends_on:
      - db
      - hasura

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: battleship
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  hasura:
    image: hasura/graphql-engine:latest
    ports:
      - "8080:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://user:password@db:5432/battleship
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
    depends_on:
      - db

volumes:
  db_data:
